use_frameworks!

target 'JMMessageInput_Example' do
	platform :ios, '10.0'

  pod 'JMMessageInput', '~> 0.1.1'
  pod 'JMContainerControllers', '~> 0.1.0'


  target 'JMMessageInput_Tests' do
    inherit! :search_paths

    
  end
end
